import type { Metadata } from 'next'
import { PrimeReactProvider } from 'primereact/api'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { SpeedDial } from 'primereact/speeddial'


import 'primeflex/primeflex.css'
import 'primereact/resources/primereact.css'
import 'primereact/resources/themes/arya-orange/theme.css'
import 'primeicons/primeicons.css'
import { Tooltip } from 'primereact/tooltip'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const items = [
  {
    label: 'Calendario',
    icon: 'pi pi-calendar'
  },
  {
    label: 'Ordenes',
    icon: 'pi pi-book'
  },
  {
    label: 'Clientes',
    icon: 'pi pi-address-book'
  },
  {
    label: 'Automoviles',
    icon: 'pi pi-car'
  },
  {
    label: 'Configuración',
    icon: 'pi pi-cog'
  }
]

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {

  const value = {
    ripple: true
  }


  return (
    <html lang="es">
      <PrimeReactProvider value={value}>
        <body className={`${geistSans.variable} ${geistMono.variable} text-center z-1 relative`}>
          <header className=' p-4 flex align-items-center text-white h-8rem gap-5'>
            <img src="logo.png" alt="" className='w-11rem overflow-hidden ml-8 z-1'  />
            <h1 className='z-1 text-6xl hidden md:block' >Taller de autos</h1>
          </header>
          <main className='align-items-center flex flex-column'>
            {children}
          </main>
          <Tooltip target=".speeddial-bottom-left .p-speeddial-action" />
          <SpeedDial model={items} direction="up" style={{ left: '20px', bottom: '20px', position: 'fixed' }} className="speeddial-bottom-left" showIcon="pi pi-bars" hideIcon="pi pi-times"/>

        </body>
      </PrimeReactProvider>
    </html>
  )
}
